; ASCII EQUs
ASCII_END equ 0
ASCII_BELL equ 7
ASCII_BACKSPACE equ 8
ASCII_HORIZONTAL_TAB equ 9
ASCII_VERTICAL_TAB equ 11
ASCII_LINEBREAK equ 10
ASCII_CARRIAGE_RETURN equ 13
ASCII_CLEAR equ 12

; Offsets
ASCII_OFFSET_NUM equ 0x30
ASCII_OFFSET_CHAR equ 0x40
